# Generated by Django 4.0.2 on 2025-08-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_user_order_movie_duration_alter_movie_actors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
